### ISSUE TITLE
config.yml not ERB'd 

### ISSUE THREAD

**Issue by mglaze** [hammernight/taza#41]
Config.yml ERB is not parsed. 

Example: 
```yaml
browser: <% "#{ENV['BROWSER']}" %>
page_load_timeout: 60
switches:  "%w[--ignore-certificate-errors]"
driver: watir_webdriver
```
params load as:
```javascript
{ :browser=>"<% \"\#{ENV['BROWSER']}\" %>",
 :page_load_timeout=>"60",
 :switches=>"%w[--ignore-certificate-errors]",
 :driver=>"watir_webdriver",
 :attach=>false}
```
